module.exports.adminUserToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSWQiOiJhZG1pblVzZXJTZXNzaW9uIiwidXNlcklkIjoiYTljNDY2ZTItNjUyZi00ZjRlLWE3ZTAtYjgyZDE3NjhhZDIxIiwiZW1haWwiOiJhZG1pbkB0ZXN0LmNvbSIsImZpcnN0TmFtZSI6IkFkbWluIiwibGFzdE5hbWUiOiJVc2VyIiwiYWN0aXZhdGVkIjp0cnVlLCJkaXNhYmxlZCI6ZmFsc2UsImlzQWRtaW4iOnRydWUsImlhdCI6MTU0NTU4MDA5MSwiZXhwIjoxNTQ1NjIzMjkxfQ.Lz3cCn7YHWwfM2isCkIcCkI84aJeTI0FaocPbISvHBA'
module.exports.standardUserToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSWQiOiJzdGFuZGFyZFVzZXJTZXNzaW9uIiwidXNlcklkIjoiZjg0NmViZDAtMDRjMy00YTMwLWFlNDMtZjA2NDY3Yjk1MWM0IiwiZW1haWwiOiJ1c2VyQHRlc3QuY29tIiwiZmlyc3ROYW1lIjoiVGVzdCIsImxhc3ROYW1lIjoiVXNlciIsImFjdGl2YXRlZCI6dHJ1ZSwiZGlzYWJsZWQiOmZhbHNlLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNTQ1NTgwMDkxLCJleHAiOjE1NDU2MjMyOTF9.Lj-dNtOgQZURD_eG8JVP2tVuKaiu_KX8y0LhEHLuOug'
module.exports.otherUserToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSWQiOiJvdGhlclVzZXJTZXNzaW9uIiwidXNlcklkIjoiNCIsImVtYWlsIjoib3RoZXJAdGVzdC5jb20iLCJmaXJzdE5hbWUiOiJPdGhlciIsImxhc3ROYW1lIjoiVXNlciIsImFjdGl2YXRlZCI6dHJ1ZSwiZGlzYWJsZWQiOmZhbHNlLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNTQ1NTgwMDkxLCJleHAiOjE1NDU2MjMyOTF9.e_a4E5udfG9x3SfwD5yRgptuuI0d9o6rbCneM4b-RGs'

module.exports.adminUserSessionId = 'adminUserSession'
module.exports.standardUserSessionId = 'standardUserSession'
module.exports.otherUserSessionId = 'otherUserSession'

module.exports.adminUserId = 'a9c466e2-652f-4f4e-a7e0-b82d1768ad21'
module.exports.standardUserId = 'f846ebd0-04c3-4a30-ae43-f06467b951c4'
module.exports.otherUserId = '4'
