module.exports.adminUserToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSWQiOiJhZG1pblVzZXJTZXNzaW9uIiwidXNlcklkIjoiYTljNDY2ZTItNjUyZi00ZjRlLWE3ZTAtYjgyZDE3NjhhZDIxIiwiZW1haWwiOiJhZG1pbkB0ZXN0LmNvbSIsIm5hbWUiOiJUZXN0IEFkbWluIFVzZXIiLCJhY3RpdmF0ZWQiOnRydWUsImRpc2FibGVkIjpmYWxzZSwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNTQzODM3NDgyLCJleHAiOjE1NDM4ODA2ODJ9.Id8jjXcEfQsil-1AmMbzFWevityfsk55-X5xCAdhxyE'
module.exports.standardUserToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSWQiOiJzdGFuZGFyZFVzZXJTZXNzaW9uIiwidXNlcklkIjoiZjg0NmViZDAtMDRjMy00YTMwLWFlNDMtZjA2NDY3Yjk1MWM0IiwiZW1haWwiOiJ1c2VyQHRlc3QuY29tIiwibmFtZSI6IlRlc3QgVXNlciIsImFjdGl2YXRlZCI6dHJ1ZSwiZGlzYWJsZWQiOmZhbHNlLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNTQzODM3NDgyLCJleHAiOjE1NDM4ODA2ODJ9.gpfOxbzyOAaCIW-uvo47-b__3AsyChZKjNJE8GGPdZ4'
module.exports.otherUserToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSWQiOiJvdGhlclVzZXJTZXNzaW9uIiwidXNlcklkIjoiNCIsImVtYWlsIjoib3RoZXJAdGVzdC5jb20iLCJuYW1lIjoiT3RoZXIgVGVzdCBVc2VyIiwiYWN0aXZhdGVkIjp0cnVlLCJkaXNhYmxlZCI6ZmFsc2UsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE1NDM4NDY1MTIsImV4cCI6MTU0Mzg4OTcxMn0.zz4XSiPYExxS4Uuda-QpdnYKXQUSO6Sgq3ys2UGuRO0'

module.exports.adminUserSessionId = 'adminUserSession'
module.exports.standardUserSessionId = 'standardUserSession'
module.exports.otherUserSessionId = 'otherUserSession'

module.exports.adminUserId = 'a9c466e2-652f-4f4e-a7e0-b82d1768ad21'
module.exports.standardUserId = 'f846ebd0-04c3-4a30-ae43-f06467b951c4'
module.exports.otherUserId = '4'
